### ISSUE TITLE
ak.argsort(ak.Strings) is unstable

### ISSUE THREAD

**Issue by gnat79** [mhmerrill/arkouda#304] opened 2020-02-28 14:31 UTC
Working on large ak.Strings arrays (say, 5 million values), argsort does not always return the same permutation, even when the values in the string are unique.

On smaller arrays argsort appears to be working fine, and I do not have an estimate of what size is needed, or even if size is a significant factor.

**Comment by gnat79** [comment] 2020-02-28 17:04
A further behavior I've noticed is that a small percentage of strings are becoming garbled. About half of  the garbled strings have a single character that was garbled to a null byte `\x00`, and about half of them are printable character changes.

For context, on an array of 30 million strings, I found 9 garbles in my most recent test. The number varies, but the order of magnitude is the same.

**Comment by rahulghangas** [comment] 2020-03-04 01:24
Hi @gnat79, I'm unable to reproduce the argsort instability on a single locale. How many locales are you using? Here's a random dataset I created [testdump](https://drive.google.com/file/d/1rbfVWCzWTqPHAdquL9hzNfZDCDAHnvIn/view?usp=sharing)

You can load it into a list as follows
```python
import pickle
with open("test.txt", "rb") as fp:
    b = pickle.load(fp)
````

Does it show unexpected behavior as before?

**Comment by gnat79** [comment] 2020-03-04 13:11
Hi @rahulghangas, I'm not sure if this is hardware specific. I'm hoping @reuster986 would have a better understanding of that, and I'm not able to do any more testing for the time being, but I'm sure others will be able to track this down. Thanks!

**Comment by reuster986** [comment] 2020-03-09 17:35
@rahulghangas I believe this behavior was XC-specific, and I think it has the same root as #301 . I re-ran @gnat79 's reproducer after applying the patch from that issue and got the correct result, so I am going to close this for now on the assumption that the same patch fixed it.

**Closed by reuster986** 2020-03-09 17:35 UTC
