### ISSUE TITLE
Categorical in1d bug

### ISSUE THREAD

**Issue by reuster986** [mhmerrill/arkouda#730] opened 2021-04-05 13:36 UTC
The expression `f = ak.in1d(a, b)` should work when `a` and `b` are `Categorical`, but it gives a `TypeError`. It works fine when `a` is `Categorical` and `b` is `Strings`, but the case when they are both `Categorical` is unhandled.

**Comment by hokiegeek2** [comment] 2021-04-06 10:37
The issue is that we're checking for the in1d attribute (method) in the Categorical object, but hasattr returns false:

![image](https://user-images.githubusercontent.com/10785153/113694168-6b59a100-969d-11eb-8de1-2854610caf6d.png)

As a direct consequence, the type checking within the pdarraysetops.in1d method fails to account for Categorical objects.

I fixed this by specifying 'categories' for the attribute we're checking for:

![image](https://user-images.githubusercontent.com/10785153/113698503-867adf80-96a2-11eb-88cd-b99d55df0712.png)

**Comment by hokiegeek2** [comment] 2021-04-06 10:48
The next problem is that the pdarraysetops.in1d method delegates to the Catgorical.in1d method:

![image](https://user-images.githubusercontent.com/10785153/113699156-37817a00-96a3-11eb-8c1a-7bfa072ba067.png)

The Categorical.in1d method in turn delegates to the pdarraysetops.in1d method, passing in it's own categories attribute (of type Strings) and the other Categorical object:

![image](https://user-images.githubusercontent.com/10785153/113699479-9b0ba780-96a3-11eb-9096-243344ac5734.png)

There is currently no support for the combo of a Categorical and Strings object being passed into the pdarraysetops.in1d method, which causes the TypeError to be raised:

![image](https://user-images.githubusercontent.com/10785153/113699661-df974300-96a3-11eb-97cb-ca256a18b101.png)

![image](https://user-images.githubusercontent.com/10785153/113699732-f473d680-96a3-11eb-9956-bb74587006e7.png)

**Comment by hokiegeek2** [comment] 2021-04-06 16:02
[PR](https://github.com/mhmerrill/arkouda/pull/733) submitted

**Comment by hokiegeek2** [comment] 2021-04-07 10:31
[PR](https://github.com/mhmerrill/arkouda/pull/733) approved and merged, issue resolved.

**Closed by hokiegeek2** 2021-04-07 10:31 UTC
Labels: bug
