### ISSUE TITLE
Chapel test error

### ISSUE THREAD

**Issue by hokiegeek2** [mhmerrill/arkouda#347] opened 2020-04-08 14:53 UTC
Hi Guys,

I am seeing the following Chapel test error following a pull from the master branch:

![image](https://user-images.githubusercontent.com/10785153/78798458-046cb380-7987-11ea-96e9-b036ae59245b.png)

**Comment by ronawho** [comment] 2020-04-08 16:19
I believe this is a duplicate of https://github.com/mhmerrill/arkouda/issues/214

**Closed** 2020-05-15 19:38 UTC
