### ISSUE TITLE
io_test failures after #553 

### ISSUE THREAD

**Issue by ronawho** [mhmerrill/arkouda#556] opened 2020-11-03 20:17 UTC
https://github.com/mhmerrill/arkouda/pull/553 changed a [spawn call](https://github.com/mhmerrill/arkouda/pull/553/files#diff-394b8a344150500f3214611a8f8716ecb550bf84cb725c8ff705fec3437ff952R197) to use `stderr=PIPE,stdout=PIPE`. Unfortunately, piping stderr/stdout is not supported under Aries (ugni) or InfiniBand (gasnet-ibv):
 - https://github.com/chapel-lang/chapel/issues/7550
 - https://github.com/chapel-lang/chapel/issues/13387

The ugni issue is documented in the [spawn documentation](https://chapel-lang.org/docs/modules/standard/Spawn.html), though there is a similar issue for InfiniBand. Under ugni we get:

```
RuntimeError: Error: failed to spawn process and read output "SystemError: Invalid argument (spawn with more than 1 locale for CHPL_COMM=ugni with hugepages currently requires stdin, stdout, stderr=FORWARD)"
```

And under InfiniBand we're just hitting a segfault since there currently isn't a chapel level error being thrown, though we (the Chapel team) should add one.

---

Not being able to spawn things like this is general problem in HPC beyond just Chapel. `fork` doesn't work in configurations where memory has to be registered with the NIC. When not piping, we're able to use something other than fork, but when piping fork is the only option.

As a simple fix you could just capture the h5ls stderr to a different file and read that in separately (`h5ls filename > tmpFile 2> tmpFileStderr`), but a more principled solution might be to stop shelling out to `h5ls` and use the C api directly. That would also resolve https://github.com/mhmerrill/arkouda/issues/452

If better spawn support is important, we may be able to do something. Under IB you can set `IBV_FORK_SAFE=1` but that has performance implications. I'm not sure what the path forward would be for ugni though.

**Comment by ronawho** [comment] 2020-11-03 20:17
FYI @hokiegeek2

**Comment by hokiegeek2** [comment] 2020-11-03 20:22
@ronawho @mhmerrill @reuster986 I am on it now.

**Comment by hokiegeek2** [comment] 2020-11-03 20:53
@ronawho i vote for better spawn support that enables direct capture of logging messages. In the meantime, I will work on getting the logging output to tmp file

**Comment by ronawho** [comment] 2020-11-03 21:51
It's not an area I'm very familiar with, but fork support in HPC is a hard problem in general. I know there's a performance hit to supporting it under InfiniBand, and I'm not sure how possible it is for Aries. I'm not sure how much the performance overhead is for IB, but I suspect it's not trivial or they would support it by default.

**Comment by gbtitus** [comment] 2020-11-03 22:09
We could support fork on XC with comm=ugni but only with so-called "minimal registration" mode, where we register a small amount of comm layer managed memory that absolutely has to be NIC-accessible, and leave the user memory unregistered.  There is code for this in the comm layer but the capability is not documented and may or may not work in all cases.  (It was never tested extensively and may have bit-rotted since what little testing occurred was done.)  The major side effect of using this mode is that all communication has to be done through (registered) bounce buffers, so the performance is correspondingly poor.

**Comment by ronawho** [comment] 2020-11-03 22:15
Right, but like you said minimal registration kills performance. The IB performance hit from `IBV_FORK_SAFE=1` might be something like a 1-5% performance loss, but ugni minimal registration will probably have like a 10-20x performance hit for Arkouda so I don't think that's useable.

**Comment by gbtitus** [comment] 2020-11-03 22:32
Yes, the performance is very bad.  I was responding to "how possible [fork support] is for Aries", where by "Aries" I assumed we were talking about the network of that name rather than for example the GASNet conduit.  (Since the root cause of the difficulty on XC has to do with copy-on-write not working with the hugepages which are necessary for comm performance, something that is independent of which comm layer one uses.)

**Comment by hokiegeek2** [comment] 2020-11-04 11:43
@ronawho I have a PR with a fix for this awaiting review by you and @mhmerrill

**Comment by hokiegeek2** [comment] 2020-11-04 21:19
fixed bug, PR merged, issue resolved.

**Closed by hokiegeek2** 2020-11-04 21:19 UTC
